/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSpecialitiesIndexRouteImport } from './routes/_authenticated/specialities/index'
import { Route as AuthenticatedSmsLogsIndexRouteImport } from './routes/_authenticated/sms-logs/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHospitalsIndexRouteImport } from './routes/_authenticated/hospitals/index'
import { Route as AuthenticatedHomeDoctorBookingsIndexRouteImport } from './routes/_authenticated/home-doctor-bookings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGuideBookingsIndexRouteImport } from './routes/_authenticated/guide-bookings/index'
import { Route as AuthenticatedDoctorsIndexRouteImport } from './routes/_authenticated/doctors/index'
import { Route as AuthenticatedDoctorLiveQueuesIndexRouteImport } from './routes/_authenticated/doctor-live-queues/index'
import { Route as AuthenticatedDoctorHomeSchedulesIndexRouteImport } from './routes/_authenticated/doctor-home-schedules/index'
import { Route as AuthenticatedContactMessagesIndexRouteImport } from './routes/_authenticated/contact-messages/index'
import { Route as AuthenticatedConcentrationsIndexRouteImport } from './routes/_authenticated/concentrations/index'
import { Route as AuthenticatedCallbackRequestsIndexRouteImport } from './routes/_authenticated/callback-requests/index'
import { Route as AuthenticatedBdLocationsIndexRouteImport } from './routes/_authenticated/bd-locations/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAppointmentsIndexRouteImport } from './routes/_authenticated/appointments/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDoctorsIdRouteImport } from './routes/_authenticated/doctors/$id'
import { Route as AuthenticatedHospitalsIdIndexRouteImport } from './routes/_authenticated/hospitals/$id/index'
import { Route as AuthenticatedHospitalsIdTeamRouteImport } from './routes/_authenticated/hospitals/$id/team'

const AuthenticatedLabsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/labs/',
)()
const AuthenticatedDiagnosticTestsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/diagnostic-tests/',
)()
const AuthenticatedDiagnosticBookingsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/diagnostic-bookings/',
)()
const AuthenticatedAmbulancesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/ambulances/',
)()
const AuthenticatedAmbulanceBookingsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/ambulance-bookings/',
)()

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabsIndexLazyRoute =
  AuthenticatedLabsIndexLazyRouteImport.update({
    id: '/labs/',
    path: '/labs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/labs/index.lazy').then((d) => d.Route),
  )
const AuthenticatedDiagnosticTestsIndexLazyRoute =
  AuthenticatedDiagnosticTestsIndexLazyRouteImport.update({
    id: '/diagnostic-tests/',
    path: '/diagnostic-tests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/diagnostic-tests/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDiagnosticBookingsIndexLazyRoute =
  AuthenticatedDiagnosticBookingsIndexLazyRouteImport.update({
    id: '/diagnostic-bookings/',
    path: '/diagnostic-bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/diagnostic-bookings/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAmbulancesIndexLazyRoute =
  AuthenticatedAmbulancesIndexLazyRouteImport.update({
    id: '/ambulances/',
    path: '/ambulances/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ambulances/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAmbulanceBookingsIndexLazyRoute =
  AuthenticatedAmbulanceBookingsIndexLazyRouteImport.update({
    id: '/ambulance-bookings/',
    path: '/ambulance-bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/ambulance-bookings/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpecialitiesIndexRoute =
  AuthenticatedSpecialitiesIndexRouteImport.update({
    id: '/specialities/',
    path: '/specialities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSmsLogsIndexRoute =
  AuthenticatedSmsLogsIndexRouteImport.update({
    id: '/sms-logs/',
    path: '/sms-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHospitalsIndexRoute =
  AuthenticatedHospitalsIndexRouteImport.update({
    id: '/hospitals/',
    path: '/hospitals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeDoctorBookingsIndexRoute =
  AuthenticatedHomeDoctorBookingsIndexRouteImport.update({
    id: '/home-doctor-bookings/',
    path: '/home-doctor-bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuideBookingsIndexRoute =
  AuthenticatedGuideBookingsIndexRouteImport.update({
    id: '/guide-bookings/',
    path: '/guide-bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorsIndexRoute =
  AuthenticatedDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorLiveQueuesIndexRoute =
  AuthenticatedDoctorLiveQueuesIndexRouteImport.update({
    id: '/doctor-live-queues/',
    path: '/doctor-live-queues/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorHomeSchedulesIndexRoute =
  AuthenticatedDoctorHomeSchedulesIndexRouteImport.update({
    id: '/doctor-home-schedules/',
    path: '/doctor-home-schedules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactMessagesIndexRoute =
  AuthenticatedContactMessagesIndexRouteImport.update({
    id: '/contact-messages/',
    path: '/contact-messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConcentrationsIndexRoute =
  AuthenticatedConcentrationsIndexRouteImport.update({
    id: '/concentrations/',
    path: '/concentrations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCallbackRequestsIndexRoute =
  AuthenticatedCallbackRequestsIndexRouteImport.update({
    id: '/callback-requests/',
    path: '/callback-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBdLocationsIndexRoute =
  AuthenticatedBdLocationsIndexRouteImport.update({
    id: '/bd-locations/',
    path: '/bd-locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsIndexRoute =
  AuthenticatedAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorsIdRoute = AuthenticatedDoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHospitalsIdIndexRoute =
  AuthenticatedHospitalsIdIndexRouteImport.update({
    id: '/hospitals/$id/',
    path: '/hospitals/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHospitalsIdTeamRoute =
  AuthenticatedHospitalsIdTeamRouteImport.update({
    id: '/hospitals/$id/team',
    path: '/hospitals/$id/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/doctors/$id': typeof AuthenticatedDoctorsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/bd-locations/': typeof AuthenticatedBdLocationsIndexRoute
  '/callback-requests/': typeof AuthenticatedCallbackRequestsIndexRoute
  '/concentrations/': typeof AuthenticatedConcentrationsIndexRoute
  '/contact-messages/': typeof AuthenticatedContactMessagesIndexRoute
  '/doctor-home-schedules/': typeof AuthenticatedDoctorHomeSchedulesIndexRoute
  '/doctor-live-queues/': typeof AuthenticatedDoctorLiveQueuesIndexRoute
  '/doctors/': typeof AuthenticatedDoctorsIndexRoute
  '/guide-bookings/': typeof AuthenticatedGuideBookingsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/home-doctor-bookings/': typeof AuthenticatedHomeDoctorBookingsIndexRoute
  '/hospitals/': typeof AuthenticatedHospitalsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/sms-logs/': typeof AuthenticatedSmsLogsIndexRoute
  '/specialities/': typeof AuthenticatedSpecialitiesIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/ambulance-bookings/': typeof AuthenticatedAmbulanceBookingsIndexLazyRoute
  '/ambulances/': typeof AuthenticatedAmbulancesIndexLazyRoute
  '/diagnostic-bookings/': typeof AuthenticatedDiagnosticBookingsIndexLazyRoute
  '/diagnostic-tests/': typeof AuthenticatedDiagnosticTestsIndexLazyRoute
  '/labs/': typeof AuthenticatedLabsIndexLazyRoute
  '/hospitals/$id/team': typeof AuthenticatedHospitalsIdTeamRoute
  '/hospitals/$id/': typeof AuthenticatedHospitalsIdIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/doctors/$id': typeof AuthenticatedDoctorsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/bd-locations': typeof AuthenticatedBdLocationsIndexRoute
  '/callback-requests': typeof AuthenticatedCallbackRequestsIndexRoute
  '/concentrations': typeof AuthenticatedConcentrationsIndexRoute
  '/contact-messages': typeof AuthenticatedContactMessagesIndexRoute
  '/doctor-home-schedules': typeof AuthenticatedDoctorHomeSchedulesIndexRoute
  '/doctor-live-queues': typeof AuthenticatedDoctorLiveQueuesIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/guide-bookings': typeof AuthenticatedGuideBookingsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/home-doctor-bookings': typeof AuthenticatedHomeDoctorBookingsIndexRoute
  '/hospitals': typeof AuthenticatedHospitalsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sms-logs': typeof AuthenticatedSmsLogsIndexRoute
  '/specialities': typeof AuthenticatedSpecialitiesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/ambulance-bookings': typeof AuthenticatedAmbulanceBookingsIndexLazyRoute
  '/ambulances': typeof AuthenticatedAmbulancesIndexLazyRoute
  '/diagnostic-bookings': typeof AuthenticatedDiagnosticBookingsIndexLazyRoute
  '/diagnostic-tests': typeof AuthenticatedDiagnosticTestsIndexLazyRoute
  '/labs': typeof AuthenticatedLabsIndexLazyRoute
  '/hospitals/$id/team': typeof AuthenticatedHospitalsIdTeamRoute
  '/hospitals/$id': typeof AuthenticatedHospitalsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/doctors/$id': typeof AuthenticatedDoctorsIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/bd-locations/': typeof AuthenticatedBdLocationsIndexRoute
  '/_authenticated/callback-requests/': typeof AuthenticatedCallbackRequestsIndexRoute
  '/_authenticated/concentrations/': typeof AuthenticatedConcentrationsIndexRoute
  '/_authenticated/contact-messages/': typeof AuthenticatedContactMessagesIndexRoute
  '/_authenticated/doctor-home-schedules/': typeof AuthenticatedDoctorHomeSchedulesIndexRoute
  '/_authenticated/doctor-live-queues/': typeof AuthenticatedDoctorLiveQueuesIndexRoute
  '/_authenticated/doctors/': typeof AuthenticatedDoctorsIndexRoute
  '/_authenticated/guide-bookings/': typeof AuthenticatedGuideBookingsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/home-doctor-bookings/': typeof AuthenticatedHomeDoctorBookingsIndexRoute
  '/_authenticated/hospitals/': typeof AuthenticatedHospitalsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sms-logs/': typeof AuthenticatedSmsLogsIndexRoute
  '/_authenticated/specialities/': typeof AuthenticatedSpecialitiesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/ambulance-bookings/': typeof AuthenticatedAmbulanceBookingsIndexLazyRoute
  '/_authenticated/ambulances/': typeof AuthenticatedAmbulancesIndexLazyRoute
  '/_authenticated/diagnostic-bookings/': typeof AuthenticatedDiagnosticBookingsIndexLazyRoute
  '/_authenticated/diagnostic-tests/': typeof AuthenticatedDiagnosticTestsIndexLazyRoute
  '/_authenticated/labs/': typeof AuthenticatedLabsIndexLazyRoute
  '/_authenticated/hospitals/$id/team': typeof AuthenticatedHospitalsIdTeamRoute
  '/_authenticated/hospitals/$id/': typeof AuthenticatedHospitalsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/doctors/$id'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/appointments/'
    | '/apps/'
    | '/bd-locations/'
    | '/callback-requests/'
    | '/concentrations/'
    | '/contact-messages/'
    | '/doctor-home-schedules/'
    | '/doctor-live-queues/'
    | '/doctors/'
    | '/guide-bookings/'
    | '/help-center/'
    | '/home-doctor-bookings/'
    | '/hospitals/'
    | '/settings/'
    | '/sms-logs/'
    | '/specialities/'
    | '/tasks/'
    | '/users/'
    | '/ambulance-bookings/'
    | '/ambulances/'
    | '/diagnostic-bookings/'
    | '/diagnostic-tests/'
    | '/labs/'
    | '/hospitals/$id/team'
    | '/hospitals/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/doctors/$id'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/appointments'
    | '/apps'
    | '/bd-locations'
    | '/callback-requests'
    | '/concentrations'
    | '/contact-messages'
    | '/doctor-home-schedules'
    | '/doctor-live-queues'
    | '/doctors'
    | '/guide-bookings'
    | '/help-center'
    | '/home-doctor-bookings'
    | '/hospitals'
    | '/settings'
    | '/sms-logs'
    | '/specialities'
    | '/tasks'
    | '/users'
    | '/ambulance-bookings'
    | '/ambulances'
    | '/diagnostic-bookings'
    | '/diagnostic-tests'
    | '/labs'
    | '/hospitals/$id/team'
    | '/hospitals/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/doctors/$id'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/appointments/'
    | '/_authenticated/apps/'
    | '/_authenticated/bd-locations/'
    | '/_authenticated/callback-requests/'
    | '/_authenticated/concentrations/'
    | '/_authenticated/contact-messages/'
    | '/_authenticated/doctor-home-schedules/'
    | '/_authenticated/doctor-live-queues/'
    | '/_authenticated/doctors/'
    | '/_authenticated/guide-bookings/'
    | '/_authenticated/help-center/'
    | '/_authenticated/home-doctor-bookings/'
    | '/_authenticated/hospitals/'
    | '/_authenticated/settings/'
    | '/_authenticated/sms-logs/'
    | '/_authenticated/specialities/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/ambulance-bookings/'
    | '/_authenticated/ambulances/'
    | '/_authenticated/diagnostic-bookings/'
    | '/_authenticated/diagnostic-tests/'
    | '/_authenticated/labs/'
    | '/_authenticated/hospitals/$id/team'
    | '/_authenticated/hospitals/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs/': {
      id: '/_authenticated/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof AuthenticatedLabsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostic-tests/': {
      id: '/_authenticated/diagnostic-tests/'
      path: '/diagnostic-tests'
      fullPath: '/diagnostic-tests/'
      preLoaderRoute: typeof AuthenticatedDiagnosticTestsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostic-bookings/': {
      id: '/_authenticated/diagnostic-bookings/'
      path: '/diagnostic-bookings'
      fullPath: '/diagnostic-bookings/'
      preLoaderRoute: typeof AuthenticatedDiagnosticBookingsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ambulances/': {
      id: '/_authenticated/ambulances/'
      path: '/ambulances'
      fullPath: '/ambulances/'
      preLoaderRoute: typeof AuthenticatedAmbulancesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ambulance-bookings/': {
      id: '/_authenticated/ambulance-bookings/'
      path: '/ambulance-bookings'
      fullPath: '/ambulance-bookings/'
      preLoaderRoute: typeof AuthenticatedAmbulanceBookingsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/specialities/': {
      id: '/_authenticated/specialities/'
      path: '/specialities'
      fullPath: '/specialities/'
      preLoaderRoute: typeof AuthenticatedSpecialitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms-logs/': {
      id: '/_authenticated/sms-logs/'
      path: '/sms-logs'
      fullPath: '/sms-logs/'
      preLoaderRoute: typeof AuthenticatedSmsLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/hospitals/': {
      id: '/_authenticated/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof AuthenticatedHospitalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home-doctor-bookings/': {
      id: '/_authenticated/home-doctor-bookings/'
      path: '/home-doctor-bookings'
      fullPath: '/home-doctor-bookings/'
      preLoaderRoute: typeof AuthenticatedHomeDoctorBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide-bookings/': {
      id: '/_authenticated/guide-bookings/'
      path: '/guide-bookings'
      fullPath: '/guide-bookings/'
      preLoaderRoute: typeof AuthenticatedGuideBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors/': {
      id: '/_authenticated/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof AuthenticatedDoctorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor-live-queues/': {
      id: '/_authenticated/doctor-live-queues/'
      path: '/doctor-live-queues'
      fullPath: '/doctor-live-queues/'
      preLoaderRoute: typeof AuthenticatedDoctorLiveQueuesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor-home-schedules/': {
      id: '/_authenticated/doctor-home-schedules/'
      path: '/doctor-home-schedules'
      fullPath: '/doctor-home-schedules/'
      preLoaderRoute: typeof AuthenticatedDoctorHomeSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact-messages/': {
      id: '/_authenticated/contact-messages/'
      path: '/contact-messages'
      fullPath: '/contact-messages/'
      preLoaderRoute: typeof AuthenticatedContactMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concentrations/': {
      id: '/_authenticated/concentrations/'
      path: '/concentrations'
      fullPath: '/concentrations/'
      preLoaderRoute: typeof AuthenticatedConcentrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/callback-requests/': {
      id: '/_authenticated/callback-requests/'
      path: '/callback-requests'
      fullPath: '/callback-requests/'
      preLoaderRoute: typeof AuthenticatedCallbackRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bd-locations/': {
      id: '/_authenticated/bd-locations/'
      path: '/bd-locations'
      fullPath: '/bd-locations/'
      preLoaderRoute: typeof AuthenticatedBdLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors/$id': {
      id: '/_authenticated/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof AuthenticatedDoctorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospitals/$id/': {
      id: '/_authenticated/hospitals/$id/'
      path: '/hospitals/$id'
      fullPath: '/hospitals/$id/'
      preLoaderRoute: typeof AuthenticatedHospitalsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospitals/$id/team': {
      id: '/_authenticated/hospitals/$id/team'
      path: '/hospitals/$id/team'
      fullPath: '/hospitals/$id/team'
      preLoaderRoute: typeof AuthenticatedHospitalsIdTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDoctorsIdRoute: typeof AuthenticatedDoctorsIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppointmentsIndexRoute: typeof AuthenticatedAppointmentsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBdLocationsIndexRoute: typeof AuthenticatedBdLocationsIndexRoute
  AuthenticatedCallbackRequestsIndexRoute: typeof AuthenticatedCallbackRequestsIndexRoute
  AuthenticatedConcentrationsIndexRoute: typeof AuthenticatedConcentrationsIndexRoute
  AuthenticatedContactMessagesIndexRoute: typeof AuthenticatedContactMessagesIndexRoute
  AuthenticatedDoctorHomeSchedulesIndexRoute: typeof AuthenticatedDoctorHomeSchedulesIndexRoute
  AuthenticatedDoctorLiveQueuesIndexRoute: typeof AuthenticatedDoctorLiveQueuesIndexRoute
  AuthenticatedDoctorsIndexRoute: typeof AuthenticatedDoctorsIndexRoute
  AuthenticatedGuideBookingsIndexRoute: typeof AuthenticatedGuideBookingsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHomeDoctorBookingsIndexRoute: typeof AuthenticatedHomeDoctorBookingsIndexRoute
  AuthenticatedHospitalsIndexRoute: typeof AuthenticatedHospitalsIndexRoute
  AuthenticatedSmsLogsIndexRoute: typeof AuthenticatedSmsLogsIndexRoute
  AuthenticatedSpecialitiesIndexRoute: typeof AuthenticatedSpecialitiesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAmbulanceBookingsIndexLazyRoute: typeof AuthenticatedAmbulanceBookingsIndexLazyRoute
  AuthenticatedAmbulancesIndexLazyRoute: typeof AuthenticatedAmbulancesIndexLazyRoute
  AuthenticatedDiagnosticBookingsIndexLazyRoute: typeof AuthenticatedDiagnosticBookingsIndexLazyRoute
  AuthenticatedDiagnosticTestsIndexLazyRoute: typeof AuthenticatedDiagnosticTestsIndexLazyRoute
  AuthenticatedLabsIndexLazyRoute: typeof AuthenticatedLabsIndexLazyRoute
  AuthenticatedHospitalsIdTeamRoute: typeof AuthenticatedHospitalsIdTeamRoute
  AuthenticatedHospitalsIdIndexRoute: typeof AuthenticatedHospitalsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDoctorsIdRoute: AuthenticatedDoctorsIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppointmentsIndexRoute: AuthenticatedAppointmentsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBdLocationsIndexRoute: AuthenticatedBdLocationsIndexRoute,
  AuthenticatedCallbackRequestsIndexRoute:
    AuthenticatedCallbackRequestsIndexRoute,
  AuthenticatedConcentrationsIndexRoute: AuthenticatedConcentrationsIndexRoute,
  AuthenticatedContactMessagesIndexRoute:
    AuthenticatedContactMessagesIndexRoute,
  AuthenticatedDoctorHomeSchedulesIndexRoute:
    AuthenticatedDoctorHomeSchedulesIndexRoute,
  AuthenticatedDoctorLiveQueuesIndexRoute:
    AuthenticatedDoctorLiveQueuesIndexRoute,
  AuthenticatedDoctorsIndexRoute: AuthenticatedDoctorsIndexRoute,
  AuthenticatedGuideBookingsIndexRoute: AuthenticatedGuideBookingsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHomeDoctorBookingsIndexRoute:
    AuthenticatedHomeDoctorBookingsIndexRoute,
  AuthenticatedHospitalsIndexRoute: AuthenticatedHospitalsIndexRoute,
  AuthenticatedSmsLogsIndexRoute: AuthenticatedSmsLogsIndexRoute,
  AuthenticatedSpecialitiesIndexRoute: AuthenticatedSpecialitiesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAmbulanceBookingsIndexLazyRoute:
    AuthenticatedAmbulanceBookingsIndexLazyRoute,
  AuthenticatedAmbulancesIndexLazyRoute: AuthenticatedAmbulancesIndexLazyRoute,
  AuthenticatedDiagnosticBookingsIndexLazyRoute:
    AuthenticatedDiagnosticBookingsIndexLazyRoute,
  AuthenticatedDiagnosticTestsIndexLazyRoute:
    AuthenticatedDiagnosticTestsIndexLazyRoute,
  AuthenticatedLabsIndexLazyRoute: AuthenticatedLabsIndexLazyRoute,
  AuthenticatedHospitalsIdTeamRoute: AuthenticatedHospitalsIdTeamRoute,
  AuthenticatedHospitalsIdIndexRoute: AuthenticatedHospitalsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
