import { PageHeader } from "@/components/common/page-header";
import { SITE } from "@/config/site";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Read My Doctor's privacy policy — how we collect, use, protect, and share your personal health data on our platform in Bangladesh.",
  alternates: { canonical: "https://mydoctor.com.bd/privacy-policy" },
};

export default function PrivacyPolicyPage() {
  return (
    <main className="bg-background min-h-screen">
      <PageHeader
        title="Privacy Policy"
        description="Learn how we collect, use, and protect your personal information."
        breadcrumb={[{ label: "Privacy Policy", active: true }]}
      />

      <div className="container mx-auto max-w-4xl px-4 py-12 md:py-16">
        <div className="space-y-12">
          <section>
            <h2 className="text-foreground mb-4 text-2xl font-bold tracking-tight">
              1. Introduction & Scope
            </h2>
            <p className="text-muted-foreground text-base leading-relaxed">
              Welcome to My Doctor. We are dedicated to providing a secure and
              transparent healthcare platform for patients in Bangladesh. This
              Privacy Policy explains how we collect, process, and protect your
              information when you use our services, including doctor
              consultations, ambulance bookings, and diagnostic test scheduling.
              By using our platform, you agree to the collection and use of
              information in accordance with this policy.
            </p>
          </section>

          <section>
            <h2 className="text-foreground mb-4 text-2xl font-bold tracking-tight">
              2. Information We Collect
            </h2>
            <div className="space-y-6">
              <div>
                <h3 className="text-foreground mb-2 text-lg font-semibold">
                  A. Personal Identification Information
                </h3>
                <p className="text-muted-foreground mb-3 text-sm">
                  When you register, we collect:
                </p>
                <ul className="text-muted-foreground list-disc space-y-2 pl-6 text-sm">
                  <li>Full name, date of birth, and gender.</li>
                  <li>
                    Contact details including phone number and email address.
                  </li>
                  <li>
                    Physical address for house-call doctors and ambulance
                    routing.
                  </li>
                </ul>
              </div>
              <div>
                <h3 className="text-foreground mb-2 text-lg font-semibold">
                  B. Health & Medical Data
                </h3>
                <p className="text-muted-foreground mb-3 text-sm">
                  To provide medical services, we process:
                </p>
                <ul className="text-muted-foreground list-disc space-y-2 pl-6 text-sm">
                  <li>
                    Previous medical history and existing conditions shared by
                    you.
                  </li>
                  <li>Prescriptions, diagnostic reports, and imaging files.</li>
                  <li>Consultation notes generated by our partner doctors.</li>
                </ul>
              </div>
              <div>
                <h3 className="text-foreground mb-2 text-lg font-semibold">
                  C. Payment Information
                </h3>
                <p className="text-muted-foreground text-sm">
                  We collect payment details through secure SSLCommerz or other
                  encrypted gateways for service fees. We do not store full
                  credit card details on our local servers.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-foreground mb-4 text-2xl font-bold tracking-tight">
              3. Purpose of Data Processing
            </h2>
            <p className="text-muted-foreground mb-4 text-left text-base leading-relaxed">
              We use your data primarily to facilitate high-quality healthcare
              services:
            </p>
            <ul className="text-muted-foreground list-disc space-y-3 pl-6 text-base">
              <li>Verifying your identity for secure medical record access.</li>
              <li>
                Connecting you with BMDC verified doctors for video or chamber
                consultations.
              </li>
              <li>
                Dispatching the nearest ambulance based on your real-time
                location.
              </li>
              <li>
                Sending appointment reminders, prescription alerts, and lab
                report notifications.
              </li>
              <li>
                Improving platform performance and troubleshooting technical
                issues.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-foreground mb-4 text-2xl font-bold tracking-tight">
              4. Data Sharing & Disclosure
            </h2>
            <p className="text-muted-foreground mb-4 text-base leading-relaxed">
              Your privacy is our priority. We share your information only with:
            </p>
            <ul className="text-muted-foreground list-disc space-y-3 pl-6 text-base">
              <li>
                <strong>Medical Professionals:</strong> Only your assigned
                doctor can view your shared medical history.
              </li>
              <li>
                <strong>Diagnostic Labs:</strong> Necessary contact info and
                test requirements for home sample collection.
              </li>
              <li>
                <strong>Ambulance Providers:</strong> Phone number and location
                for emergency dispatch.
              </li>
              <li>
                <strong>Legal Requirements:</strong> If mandated by the laws of
                Bangladesh for public health or security.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-foreground mb-4 text-2xl font-bold tracking-tight">
              5. Data Security & Encryption
            </h2>
            <p className="text-muted-foreground text-base leading-relaxed">
              We implement industry-standard AES-256 encryption for data at rest
              and SSL/TLS for data in transit. Your medical records are stored
              in high-security data centers with restricted access. While we
              strive for absolute security, no system is 100% immune to all
              threats; however, we continuously update our protocols to mitigate
              risks.
            </p>
          </section>

          <section>
            <h2 className="text-foreground mb-4 text-2xl font-bold tracking-tight">
              6. Your Choice & Rights
            </h2>
            <p className="text-muted-foreground text-base leading-relaxed">
              You have the right to access your medical records at any time
              through your dashboard. You may also request data correction or
              account deletion by contacting our support team. Please note that
              certain data might be retained for legal or regulatory compliance
              as per healthcare guidelines.
            </p>
          </section>

          <section className="bg-muted/30 rounded-2xl p-8">
            <h2 className="text-foreground mb-4 text-xl font-bold tracking-tight">
              Privacy Personnel Contact
            </h2>
            <p className="text-muted-foreground text-base leading-relaxed">
              For any grievances or questions regarding your data privacy, you
              may reach our Data Protection Officer (DPO):
              <br />
              <br />
              <strong>Official Email:</strong> {SITE.contact.email}
              <br />
              <strong>Hotline:</strong> {SITE.contact.phones[0]}
              <br />
              <strong>Registered Office:</strong> {SITE.contact.address}
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
